### ISSUE TITLE
Data missing

### ISSUE THREAD

**Issue by yangleir** [biavillasboas/BroadbandSpectrum#1]
Hi, thank you for sharing the code and data. But it seems the data directory was missed. The same to the link: https://library.ucsd.edu/dc/object/bb3148999x

**Comment by biavillasboas** [comment]
Hi @yangleir,
thank you for raising this issue. I'm not sure I understand your question. Perhaps you could expand a little on what do you mean by "_the data directory was missed_" so I could help you? 

I'm assuming you checked the session [how to use this repository](https://github.com/biavillasboas/BroadbandSpectrum#how-to-use-this-repository)?
The data itself is not hosted on GitHub, the user has to download it from the UCSD Library Digital Collections, which is the link that you included in your comment. Are you having downloading issues?

**Comment by yangleir** [comment]
> Hi @yangleir, thank you for raising this issue. I'm not sure I understand your question. Perhaps you could expand a little on what do you mean by "_the data directory was missed_" so I could help you?
> 
> I'm assuming you checked the session [how to use this repository](https://github.com/biavillasboas/BroadbandSpectrum#how-to-use-this-repository)? The data itself is not hosted on GitHub, the user has to download it from the UCSD Library Digital Collections, which is the link that you included in your comment. Are you having downloading issues?

Perfect. I found the data in that link now.
I was just played by the downloading webpage. I need to click the `arrow to the right`  to change to the data file. Otherwise, I just got the `readme` file.
